mysite/ajax/urls.py
from django.urls import path
from . import views #.은 현재 폴더 의미

#'' : 경로명, view : 현재 폴더에 있는 views파일을 의미, index는 views파일에 있는 index함수 의미
# 관행적으로 views로 사용, 뒤 index는 쓰기 나름, views안에 있는 함수명
# myapp만 신경 쓰겠다.
urlpatterns = [
    #여기 이름은 같을 필요 없다.
    path('', views.index),
    path('calcform', views.calcform),
    path('calc', views.calc),
    path('loginform', views.loginform),
    path('login', views.login),
    path('uploadform', views.uploadform),
    path('upload', views.upload),
    path('runpythonform', views.runpythonform),
    path('runpython', views.runpython),
]

#form에서 요청을 해서 연산을 한다.
#/logins?id=ckt&pwd=ckt -> views.logins()
#req = {}
#views.logins(req)

mysite/myboard/urls.py
from django.urls import path
from . import views
from django.shortcuts import redirect


urlpatterns = [
    #view시스템이 아닌, 함수베이스로 이용
    path('', views.page),
    path('ajaxdel', views.ajaxdel),
    #get은 페이지번호를 요청했을때, 해당하는 페이지데이터를 한꺼번에 가져오는것
    path('ajaxget', views.ajaxget),

    path('<category>/<int:pk>/<mode>/', views.BoardView.as_view(), name="myboard"),
    #path('', lambda request: redirect('myboard', 'common', 0, 'list')),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

#admin이라는 경로에서는 아랫줄이 실행됨
#어플리케이션 한개만 만들때는 여기를 더이상 건드릴일 없다.
urlpatterns = [
    #flask 와 다르게 '/'로 하면 안된다.
    #문자열, myapp이라는 폴더에 있는 urls파일을 포함해라, 실제 어플리케이션에서 사용할 url은 여기서 정의
    #앞의 경로 + myapp의 함수명, 즉 localhost:포트번호+첫번째 파라미터, 다만, 명이 들어가면, myapp urls에서 /를 표기, 없으면, 뺀다.
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls), #실제 패키지 이름, 얘는 django가 기본적으로 가지고 있는 패키지다.
    path('ajax/', include('ajax.urls')),
    path('blog/', include('blog.urls')),
    path('myboard/', include('myboard.urls')),

    #여기에는 내가 만든 앱들을 정의를 해주어야한다.
]

mysite/myboard/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Board(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()  # 글자수에 제한 없는 텍스트
    created_date = models.DateTimeField(
        default=timezone.now)  # 날짜와 시간
    cnt = models.IntegerField(default=0)
    image = models.CharField(max_length=200, null=True, blank=True)
    category = models.CharField(max_length=10, default='common')



    def __str__(self):
        return self.title

mysite/myboard/forms.py
from django.forms import ValidationError
from django import forms
from . import models


def validator(value) :
    if len(value) < 5 : raise  ValidationError("길이가 너무 짧아요");

class BoardForm(forms.ModelForm):
    class Meta:
        model = models.Board
        fields = ['title', 'text']

    def __init__(self, *args, **kwargs):
        super(BoardForm, self).__init__(*args, **kwargs)
        self.fields['title'].validators = [validator]

mysite/myboard/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse, JsonResponse
from django.views.generic import View
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.urls import reverse

from . import forms
from . import models
from . import apps

def page(request):
    datas = [{"id":1, "name":"홍길동1"},
             {"id":2, "name":"홍길동2"},
             {"id":3, "name":"홍길동3"},
             {"id":4, "name":"홍길동4"},
             {"id":5, "name":"홍길동5"},
             {"id":6, "name":"홍길동6"},
             {"id":7, "name":"홍길동7"},
             ]  

    page = request.GET.get("page", 1)    
    #(page-1)*3:page*3

    #첫번째 파라미터는 데이터, 두번째 파라미터는 한페이지에 보여줄 데이터의 개수
    p = Paginator(datas, 3)

    #전체 데이터 중 일부 데이터만 subs에 저장, p.page(1)은 123만, p.page(2)는 456만 보여주는것을 확인할 수 있다.    
    subs = p.page(page)

    #return render(request, "myboard/page.html", {"datas":datas})
    return render(request, "myboard/page.html", {"datas":subs})

def ajaxdel(request):
    pk = request.GET.get("pk")
#pk가 pk인 object를 찾는다.
    models.Board.objects.get(pk=pk)
    #board.delete()
    
    return JsonResponse({'error':'0'})

#모듈단위 검증은 shell이 좋다.
def ajaxget(request):
    page = request.GET.get("page", 1)
    datas = models.Board.objects.all().filter(category='common')
    page = int(page)
    subs = datas[(page-1)*3:(page)*3]
    
    #p = Paginator(datas, 3)
    #subs = p.page(page)

    datas = {'datas': [ {"pk":data.pk, "title":data.title, "cnt":data.cnt} for data in subs]}
    print(datas)

    return JsonResponse(datas)

class BoardView(View) :
    def get(self, request, category, pk, mode, page):
        if  mode == 'add' :
            form = forms.BoardForm()
        elif mode == 'list' :
            username = request.session["username"]
            user = User.objects.get(username=username)
            data = models.Board.objects.all().filter(category=category)
            #print(reverse('myboard', args=('common', 0, 'list')))

            page = request.GET.get("page", 1)    
            #(page-1)*3:page*3

            #첫번째 파라미터는 데이터, 두번째 파라미터는 한페이지에 보여줄 데이터의 개수
            p = Paginator(data, 3)

            #전체 데이터 중 일부 데이터만 subs에 저장, p.page(1)은 123만, p.page(2)는 456만 보여주는것을 확인할 수 있다.    
            subs = p.page(page)
            
            context = {"datas": subs, "username": username, "category": category}

            return render(request, apps.APP + "/list2.html", context)

        elif mode ==  "detail" :
            p = get_object_or_404(models.Board, pk=pk)
            p.cnt += 1
            p.save()
            return render(request, apps.APP +"/detail.html", {"d": p,"category":category})
        elif mode == "edit" :
            post = get_object_or_404(models.Board, pk=pk)
            form = forms.BoardForm(instance=post)
        else :
            return HttpResponse("error page")

        return render(request, apps.APP +"/edit.html", {"form":form})

    def post(self, request, category, pk, mode):

        username = request.session["username"]
        user = User.objects.get(username=username)

        if pk == 0:
            form = forms.BoardForm(request.POST)
        else:
            post = get_object_or_404(models.Board, pk=pk)
            form = forms.BoardForm(request.POST, instance=post)

        if form.is_valid():
            post = form.save(commit=False)
            if pk == 0:
                post.author = user
                post.category = category
            post.save()
            return redirect("myboard", category, 0, 'list')
        return render(request, apps.APP + "/edit.html", {"form": form})

mysite/templates/myboard/base.html
<font color="red"><h1>    게시판 만들기 </h1> </font><br>
 로그인 사용자:{{username}}<br>

<a href="/myboard/data/0/list"> 자료실 </a>
<a href="/myboard/common/0/list"> 일반게시판 </a>
<a href="/myboard/etc/0/list">기타</a> <br>

{% block content %}
{% endblock %}


<br><br><br>
copy right..... <br>
서울특별시 ........

mysite/templates/myboard/detail.html
{% extends 'myboard/base.html' %}

게시물 보기 <br>

{% block content %}

{{d.title}}  <br>
{{d.text|linebreaks}}

<a href="{% url 'myboard' category d.pk  'edit' %}">수정 </a>


{% endblock %}

mysite/templates/myboard/edit.html
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

 <style>
      .bg { background-color: #eeeeee; }
      .bd { border: 1px solid #666666; }
 </style>

{% if form.title.value %}
<h1>  수정하기 </h1>
{% else %}
<h1>  신규작성</h1>
{% endif %}


<form method=post>
   {% csrf_token %}
   	{{ form.as_p }}

   <input type="submit" value="작성" >
   <input type="hidden" namge="page" value="2">

</form>

<script>
   $("#id_title").addClass('bg bd');
</script>

mysite/templates/myboard/list.html
{% extends 'myboard/base.html' %}

{% block content %}
<a href="{% url 'myboard' category 0 'add' %}">Add </a> <br>
{%  for d in data %}
<a href="{% url 'myboard' category d.pk 'detail' %}"> {{d.title}} 조횟수 {{d.cnt}} </a> <br>
{% endfor %}

{% endblock %}

mysite/templates/myboard/list2.html
{% extends 'myboard/base.html' %}

{% block content %}
<a href="{% url 'myboard' category 0 'add' %}">Add </a> <br>

<!--조회수 출력-->
{%  for d in datas %}
<a href="{% url 'myboard' category d.pk 'detail' %}"> {{d.title}} 조횟수 {{d.cnt}} </a> <br>
{% endfor %}

<!--여기부터가 네비게이션-->

{% if datas.has_other_pages %}
        {% if datas.has_previous %}
          <a href="?page={{ datas.previous_page_number }}">&laquo;</a>
        {% else %}
          <span>&laquo;</span>
        {% endif %}

        {% for i in datas.paginator.page_range %}
          {% if datas.number == i %}
            <span>{{ i }} </span>
          {% else %}
            <a href="?page={{ i }}">{{ i }}</a>
          {% endif %}
        {% endfor %}
        {% if datas.has_next %}
            <a href="?page={{ datas.next_page_number }}">&raquo;</a>
        {% else %}
            <span>&raquo;</span>
        {%endif %}
{%endif%}
<!--여기까지-->

{% endblock %}

mysite/templates/myboard/login.html
<form action="{% url 'login' %}" method=post>
    {% csrf_token %}
    username <input type=text  name=username >  <br>
    password <input type=password  name=password >  <br>
    <input type=submit value="로그인">
 </form>
 
 

mysite/templates/myboard/page.html
{%  for data in datas %}

   {{data.id}}  / {{data.name}}  <br>

{% endfor %}

{% if datas.has_other_pages %}
        {% if datas.has_previous %}
          <a href="?page={{ datas.previous_page_number }}">&laquo;</a>
        {% else %}
          <span>&laquo;</span>
        {% endif %}

        {% for i in datas.paginator.page_range %}
          {% if datas.number == i %}
            <span>{{ i }} </span>
          {% else %}
            <a href="?page={{ i }}">{{ i }}</a>
          {% endif %}
        {% endfor %}
        {% if datas.has_next %}
            <a href="?page={{ datas.next_page_number }}">&raquo;</a>
        {% else %}
            <span>&raquo;</span>
        {%endif %}
    {%endif%}

mysite/templates/myboard/pagew.html
{% for data in datas %}

    {{data.id}}/{{data.name}} <br>

{% endfor %}

<!--전체 페이지수를 알고 있으면, for 루프로 돌리면 된다.-->

<!--페이지 유무검사-->
{% if datas.has_other_pages %}
<!--이전 페이지 유무검사-->
    {% if datas.has_previous %}
        <a href = "?page={{datas.previous_page_number}}"></a>
    {% else %}

    {% for i in datas.paginator.page_range %}
      {% if datas.number == 1%}
        <span>{span{{i}}</span>}
      {% else% }
      <

<a href="?page=1">처음으로</a>
<a href="?page=1">이전으로</a>
<a href="?page=1">[1]</a>
<a href="?page=2">[2]</a>
<a href="?page=3">[3]</a>
<a href="?page=1">다음으로</a>
<a href="?page=3">마지막으로</a>